language: cpp
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Install host dependencies
    - conda install mamba -c conda-forge
    - mamba install xeus=0.24.2 cppzmq xproperty xwidgets=0.23.0 xtensor -c conda-forge
    # Install test dependencies
    - mamba install pybind11=2.4 pybind11_json=0.2.2 ipyleaflet=0.13.0 -c conda-forge
    # Install build dependencies
    - mamba install cmake
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        mamba install gxx_linux-64 -c conda-forge;
      fi
    # Activate root environment
    - source activate root
    # Testing
    - mkdir build
    - cd build
    - cmake -D CMAKE_INSTALL_PREFIX=$HOME/miniconda/ -D DOWNLOAD_GTEST=ON -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -D PYTHON_EXECUTABLE=`which python` ..
    - make -j2 install
    - make -j2 test_xleaflet
    - cd test
script:
    - ./test_xleaflet
